- project:
    name: zuulkpit/zuul-test
    check:
      jobs:
        - testjob
        - noop

- job:
    name: testjob
    parent: null
    run: testjob.yaml
    nodeset:
      nodes:
        - name: builder
          label: ubuntu-xenial
    
